set_location_assignment PIN_Y13 -to fpga_clk_50
set_location_assignment PIN_V12 -to fpga_clk_100
set_location_assignment PIN_AA4 -to fpga_dipsw_pio[3]
set_location_assignment PIN_W8 -to fpga_dipsw_pio[0]
set_location_assignment PIN_AB4 -to fpga_dipsw_pio[1]
set_location_assignment PIN_T8 -to fpga_dipsw_pio[2]
set_location_assignment PIN_U9 -to fpga_led_pio[0]
set_location_assignment PIN_AD4 -to fpga_led_pio[1]
set_location_assignment PIN_V10 -to fpga_led_pio[2]
set_location_assignment PIN_AC4 -to fpga_led_pio[3]
set_location_assignment PIN_Y4 -to fpga_button_pio[0]
set_location_assignment PIN_Y8 -to fpga_button_pio[1]
set_location_assignment PIN_Y5 -to fpga_button_pio[2]
